### PR TITLE
Adding support to multi-language and translating CORS post

### PR DESCRIPTION
**Pull request by heitorfig**
I'd like to contribute, I made an upgrade to the blog to support multi-languages and also translated the latest post to brazilian portuguese. I hope you liked it. It was a very helpful article.

### CODE REVIEW

**Comment by andryanmiller** [comment]
Hey @heitorfig–greatly appreciated! I'll review this PR shortly, sorry for not noticing it sooner!

**Comment by andryanmiller** [comment]
That was a bit longer than "shortly", apologies! Something I just realized is that GitHub Pages (which I use to host the site) only supports [these plugins](https://pages.github.com/versions/). nfortunately `jekyll-polyglot` isn't on that list. I'd be happy to integrate this translation manually, but wanted to see if you had any other ideas.

Also, part of the reason I've been dragging my feet is that I'm trying to get a loose set of licenses together for this repo. Would the following be amenable to you as a contributor?
- All **written content, including blog posts and site verbiage,** will be licensed [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/). That means people can repost frontendian content, but they have to link back to the original author, which would be you in the case of the translation.
- All **code** will be licensed MIT.
- The frontendian name and logo are trademarks belonging to me.

You're the first official contributor so it's only fitting you get to help shape the licensing! :)

**Comment by heitorfig** [comment]
I see, I had no idea that Pages does not support other plugins. I took a look at this [issue](https://github.com/github/pages-gem/issues/401), there is a thread about adding a multilingual plugin to Pages, but I think they are stuck on find the best/secure one. Perhaps, doing it manually, as you said, is the best approach for now. I'm going to take a look at [this article](https://www.sylvaindurand.org/making-jekyll-multilingual/), and see what I can do.

About the licensing, sure, I don't know a lot about licenses, but I'm going to study about it, and of course I'll try to help with what I know.

**Comment by andryanmiller** [comment]
I appreciate it @heitorfig! Let me know if there's anything I can do to help - my schedule is a bit hectic between my job and writing the weekly posts, but I'd like to help you show your translation to the world! As mentioned, I'd be happy to create a new page for it in the interim, at a URL like `/cors/pt-Br`.

**Comment by andryanmiller** [comment]
Hey @heitorfig - finally had some time this morning to think through this a bit more. Take a [look at this branch](https://github.com/andryanmiller/frontendian/tree/pt-br-idea) and let me know what you think. It's a bit of a hack, since we can't use `jekyll-polyglot`, but overall I think it feels nice. I've only added the translated post for the time being, as translating the rest of the site is a bit more than I can take on at the moment.

**Comment by kirill-galushko** [comment]
Hi, @andryanmiller @heitorfig . If you are find a compromise, I want to make PR with russian translation. Should I do it like in new branch in _translation folder?

**Comment by andryanmiller** [comment]
Hey @kirill-galushko! That should work well for the time being - I'm going to make a couple addl. tweaks here but overall I think we're close to having a nice translation system! I'll help you iron out any kinks as they come up, and thanks for being willing to translate into Russian!

**Comment by andryanmiller** [comment]
Hey @heitorfig! Finally had a large enough block of time that I was able to move the website off of Github Pages onto AWS. Now that that's the case, I'll be tidying a few things up and then switching over to the new version with your translation. I'll ping you again here when it's complete!

**Pull request merged**
